### PR TITLE
Updated provider for Keycloak 25.x

### LINKED ISSUE #48: internal server error
Hello, I have installed the provider and added client id and secret but when I want to connect I get :

Version
25.0.1

60lsGuID

### PR DESCRIPTION
**Pull request by andythorne**
Fixes #48

### CODE REVIEW

**Comment by jveski** [comment]
Fwiw I am running this branch and can confirm it works on 25.0

**Comment by chris-sanders** [comment]
Can we get this merged, I've just hit this too.

**Comment by chris-sanders** [comment]
@jveski / @andythorne is there a published release of this fork I can use until then?

**Comment by jveski** [comment]
@chris-sanders Here's the build I'm running - https://github.com/TheLab-ms/images/tree/main/keycloak-extensions

**Comment by wadahiro** [comment]
Sorry for my slow response. Thanks for the contribution!

**Pull request merged**
